### ISSUE TITLE
Ledger Statement Opening Balance Wrong if Date Filter Used

### ISSUE THREAD

**Issue by ongkhua** [prashants/webzash#27]
Viewing ledger statement with date filter in use will give wrong opening balance.  The shown opening balance does not take into account the opening balance set in the Ledger setting.

Below changes will fix this bug:
File: Model/Ledger.php
Line: 344

$op_total = 0;
if (empty($op['Ledger']['op_balance'])) {
	$op_total = 0;
} else {
	$op_total = $op['Ledger']['op_balance'];
}

$op_total_dc = $op['Ledger']['op_balance_dc'];
if (is_null($start_date)) {
	/* If start date is not specified then return here */
	return array('dc' => $op_total_dc, 'amount' => $op_total);
}

**Comment by prashants** [comment]
Did you select a start date ?

**Comment by ongkhua** [comment]
Yes I select start date. I need to see the correct opening balance even if
I select start date. May I know what's the reason of not giving the correct
opening balance if start date selected (if that was intended)

**Comment by prashants** [comment]
Including opening balance doesn't make sense if you select a start date since there might be entries between opening balance and your selected start date which will lead to incorrect total.

**Comment by ongkhua** [comment]
The opening balance already includes all the entries before the start date
I chose, it should reflect the amount at the start of the selected start
date.

Anyway it's up to you how you want webzash to behave, I already patched my
copy to work this way.  Thank you for your time.

**Comment by prashants** [comment]
Sorry I didn't read your bug report previously. Yes, its is a bug I guess. I will fix that.

Changing that the way you did it will affect the balance sheet, etc.

**Comment by ongkhua** [comment]
Oh, ok, kindly let me know when its committed, or send me the patch, thank
you.

**Comment by prashants** [comment]
You are absolutely right on this. Your patch was also correct.

Thanks.

**Comment by prashants** [comment]
Fixed it in v2.6-beta branch

**Comment by jacksumit** [comment]
Hi, Is this updated version deployed in Demo application (https://webzash.org/demo)?

I see that demo version still show incorrect balance when start date is selected.

**Comment by prashants** [comment]
Demo is still using very old version.
